root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main main.go"
bin = "tmp/main"
watch_dir = "."
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
