services:
  hestia-go:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    image: hestia-go:latest
    container_name: hestia-go
    volumes:
      - .:/app
    ports:
      - "4200:4200"
