services:
  hestia-go:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    image: hestia-go:latest
    container_name: hestia-go
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - hestia-db
    networks:
      - hestia-net
      - traefik-nseven

  hestia-db:
    image: postgres:16
    container_name: hestia-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - hestia-db-data:/var/lib/postgresql/data
    networks:
      - hestia-net
      - traefik-nseven

networks:
  hestia-net:
    name: hestia-net
    driver: bridge
  traefik-nseven:
    external: true

volumes:
  hestia-db-data: